import { test, expect } from '@playwright/test';
test('adaptive expense flow and navigation', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto('http://localhost:3000');
    await expect(page.getByText('Rp1.240.000', { exact: true })).toBeVisible();
    await expect(page.locator('.recharts-area')).toBeVisible();
    await expect(page.locator('.recharts-line')).toBeVisible();
    const forecast = await page.locator('.forecast-amount').textContent();
    await page.getByRole('button', { name: /Public Transport/ }).click();
    await expect(page.getByRole('button', { name: /Public Transport/ })).toHaveAttribute('aria-pressed', 'true');
    expect(await page.locator('.forecast-amount').textContent()).not.toBe(forecast);
    await page.getByRole('button', { name: 'Add Expense', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Add Expense', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.getByText('Rp1.155.000', { exact: true })).toBeVisible();
    await expect(page.getByText('Rp845.000', { exact: true })).toBeVisible();
    await expect(page.getByText('Coffee with friends', { exact: true })).toBeVisible();
    await expect(page.locator('.toast')).toContainText('Expense added');
    await expect(page.locator('.budget-row').filter({ hasText: 'Entertainment' })).toContainText('106%');
    await page.getByRole('button', { name: 'View all transactions' }).click();
    await page.getByRole('textbox', { name: 'Search transactions' }).fill('Coffee with friends');
    await expect(page.locator('.transaction-row')).toHaveCount(1);
    await page.getByRole('button', { name: 'Goals', exact: true }).click();
    await expect(page.getByText('A little security for tomorrow')).toBeVisible();
    await page.getByRole('button', { name: 'Overview', exact: true }).click();
    await page.getByRole('combobox', { name: 'Select month' }).selectOption('2026-08');
    await expect(page.locator('.metric.highlight').getByText('Rp2.000.000', { exact: true })).toBeVisible();
    await expect(page.getByText('No expenses in this month yet.', { exact: false })).toBeVisible();
    expect(errors).toEqual([]);
});
test('mobile layout and accessible modal dismissal', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto('http://localhost:3000');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.getByRole('button', { name: 'Add Expense', exact: true }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.getByRole('button', { name: 'Add Expense', exact: true })).toBeFocused();
});
