import { test, expect } from '@playwright/test';
test('wallet expense, transfer, insufficient funds, and new wallet', async ({ page }) => {
    await page.goto('http://localhost:3000');
    await page.getByRole('button', { name: 'Wallets', exact: true }).click();
    await expect(page.locator('.wallet-card')).toHaveCount(5);
    await expect(page.locator('.wallet-summary')).toContainText('Rp1.240.000');
    await page.getByRole('button', { name: 'Add Expense', exact: true }).click();
    await page.getByLabel('Pay from wallet').selectOption('dana');
    await page.getByRole('dialog').getByRole('button', { name: 'Add Expense', exact: true }).click();
    await expect(page.locator('.wallet-card').filter({ hasText: 'DANA' })).toContainText('Rp65.000');
    await expect(page.locator('.wallet-summary')).toContainText('Rp1.155.000');
    await page.getByRole('button', { name: 'Transfer', exact: true }).click();
    await page.getByLabel('From wallet').selectOption('bca');
    await page.getByLabel('To wallet').selectOption('dana');
    await page.getByLabel('Transfer amount (Rp)').fill('100000');
    await page.getByRole('button', { name: 'Confirm Transfer' }).click();
    await expect(page.locator('.wallet-card').filter({ hasText: 'DANA' })).toContainText('Rp165.000');
    await expect(page.locator('.wallet-summary')).toContainText('Rp1.155.000');
    await page.getByRole('button', { name: 'Add Expense', exact: true }).click();
    await page.getByLabel('Pay from wallet').selectOption('dana');
    await page.getByRole('spinbutton').fill('200000');
    await page.getByRole('dialog').getByRole('button', { name: 'Add Expense', exact: true }).click();
    await expect(page.getByRole('dialog').getByRole('alert')).toContainText('does not have enough funds');
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.getByRole('button', { name: 'Add Wallet', exact: true }).click();
    await page.getByLabel('Wallet name').fill('BNI Debit');
    await page.getByRole('button', { name: 'Save Wallet' }).click();
    await expect(page.locator('.wallet-card')).toHaveCount(6);
    await page.getByRole('button', { name: 'Overview', exact: true }).click();
    await expect(page.locator('.metric').filter({ hasText: 'Monthly Spending' })).toContainText('Rp845.000');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Wallets', exact: true }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
